let jsonString = `
{ "siteContent": [
  { "title":"Keerthika Sakthibalan" ,
    "aboutText":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam at placerat dui. Mauris purus metus, egestas vel tellus non, faucibus interdum dolor. Nam magna magna, facilisis a tortor nec, sodales semper massa. Aliquam sapien ipsum, tincidunt eu velit sed, tincidunt ornare magna. Curabitur pulvinar neque velit. Proin aliquet aliquet mi, efficitur facilisis neque auctor ut. Praesent lobortis massa quis pretium gravida. Sed eget metus euismod, mattis quam vel, ultrices tellus. Pellentesque pellentesque nulla et eros sagittis eleifend. Vivamus molestie ligula nisi, ut pellentesque dui laoreet non. Vivamus gravida, nunc sed pulvinar suscipit, quam ante tempor nisi, et gravida justo libero vitae dolor. Nulla vitae iaculis nulla, non iaculis neque. Nulla luctus enim eget enim porta, eu consequat quam tincidunt. Praesent sodales dolor non consectetur ultricies. Mauris eget nunc fermentum, facilisis lacus sit amet, lacinia ante."
  },
  { "title":"none" ,
    "aboutText":"Praesent accumsan pretium lorem vitae faucibus. Praesent laoreet nibh ut quam suscipit, a sodales diam sodales. In quis elit sed odio consequat semper a eget libero. In vehicula ligula sed leo vulputate imperdiet. Integer sit amet justo hendrerit enim suscipit rutrum sit amet sit amet ipsum. Quisque sed iaculis sapien. Nullam pellentesque lobortis velit, in scelerisque tortor semper ut."},
  { "title":"none" ,
    "aboutText":"Suspendisse vitae tempor magna, et sagittis sapien. In maximus lorem sed mi sodales, vel tempus arcu blandit. Donec viverra ante vel quam commodo, nec imperdiet erat faucibus. Morbi iaculis, purus eget consectetur malesuada, dolor arcu malesuada orci, eget eleifend eros nisi quis dolor. Aliquam scelerisque pellentesque elit, sit amet tempus mauris convallis sed. Praesent scelerisque sem eget elit iaculis, ut consequat enim iaculis. Etiam venenatis gravida sapien vestibulum rhoncus. In id metus eu turpis porttitor efficitur vel ut neque. Cras ornare porta purus a ornare. Donec dolor urna, efficitur volutpat lacinia eu, suscipit lacinia massa. Vivamus tempor ultricies dignissim."},
  { "title":"none" ,
    "aboutText":"Vestibulum vel justo porttitor, laoreet nulla at, aliquet leo. Curabitur vitae eleifend nulla. Integer a quam vestibulum, maximus erat id, finibus leo. Integer iaculis nibh vitae metus vestibulum, ut placerat ante tempor. Sed eu condimentum neque, quis varius ante. Donec eget diam arcu. Sed ac metus malesuada, rutrum justo quis, lobortis justo. Praesent sollicitudin metus sed dolor dignissim cursus."
  }
]}`;
